# Generated by Django 4.2.4 on 2023-09-15 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='おやつの種類')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.conditionrecord', verbose_name='おやつの種類')),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ごはんの種類')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.conditionrecord', verbose_name='ごはんの種類')),
            ],
        ),
    ]
