# Generated by Django 4.2.4 on 2023-09-19 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_snackcategory_foodcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='record',
        ),
        migrations.RemoveField(
            model_name='snackcategory',
            name='record',
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='food_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='record.foodcategory', verbose_name='ごはんの種類'),
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='snack_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='record.snackcategory', verbose_name='おやつの種類'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='その他'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='date',
            field=models.IntegerField(verbose_name='記録日'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='food_amount',
            field=models.IntegerField(verbose_name='ごはんの量'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='snack_amount',
            field=models.IntegerField(verbose_name='おやつの量'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='体重'),
        ),
    ]
