# Generated by Django 4.2.4 on 2023-09-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_remove_foodcategory_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionrecord',
            name='unit',
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='food_unit',
            field=models.CharField(blank=True, choices=[('gram', 'g'), ('pack', '袋'), ('stick', '本'), ('piece', '個')], max_length=50, null=True, verbose_name='夕ごはんの量の単位'),
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='snack_unit',
            field=models.CharField(blank=True, choices=[('gram', 'g'), ('pack', '袋'), ('stick', '本'), ('piece', '個')], max_length=50, null=True, verbose_name='おやつ3の量の単位'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='food_amount',
            field=models.IntegerField(verbose_name='夕ごはんの量'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='food_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='record.foodcategory', verbose_name='夕ごはんの種類'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='snack_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='おやつ3の量'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='snack_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='record.snackcategory', verbose_name='おやつ3の種類'),
        ),
    ]
