# Generated by Django 4.2.4 on 2023-09-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_remove_conditionrecord_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionrecord',
            name='food_amount_2',
            field=models.IntegerField(null=True, verbose_name='朝ごはんの量'),
        ),
    ]
