# Generated by Django 4.2.4 on 2023-09-19 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_conditionrecord_food_amount_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionrecord',
            name='food_category_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_category_2', to='record.foodcategory', verbose_name='夕ごはんの種類'),
        ),
    ]
