# Generated by Django 4.2.4 on 2023-09-19 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_conditionrecord_food_category_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditionrecord',
            old_name='food_amount_2',
            new_name='food_amount_bf',
        ),
        migrations.RenameField(
            model_name='conditionrecord',
            old_name='food_unit',
            new_name='food_unit_d',
        ),
        migrations.RemoveField(
            model_name='conditionrecord',
            name='food_amount',
        ),
        migrations.RemoveField(
            model_name='conditionrecord',
            name='food_category',
        ),
        migrations.RemoveField(
            model_name='conditionrecord',
            name='food_category_2',
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='food_amount_d',
            field=models.IntegerField(null=True, verbose_name='夕ごはんの量'),
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='food_amount_l',
            field=models.IntegerField(null=True, verbose_name='昼ごはんの量'),
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='food_category_bf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_category_bf', to='record.foodcategory', verbose_name='朝ごはんの種類'),
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='food_category_d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_category_d', to='record.foodcategory', verbose_name='夕ごはんの種類'),
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='food_category_l',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_category_l', to='record.foodcategory', verbose_name='昼ごはんの種類'),
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='food_unit_bf',
            field=models.CharField(blank=True, choices=[('gram', 'g'), ('pack', '袋'), ('stick', '本'), ('piece', '個')], max_length=50, null=True, verbose_name='朝ごはんの量の単位'),
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='food_unit_l',
            field=models.CharField(blank=True, choices=[('gram', 'g'), ('pack', '袋'), ('stick', '本'), ('piece', '個')], max_length=50, null=True, verbose_name='昼ごはんの量の単位'),
        ),
    ]
