# Generated by Django 4.2.4 on 2023-09-19 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_rename_food_amount_2_conditionrecord_food_amount_bf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditionrecord',
            old_name='snack_unit',
            new_name='snack_unit_3',
        ),
        migrations.RemoveField(
            model_name='conditionrecord',
            name='snack_amount',
        ),
        migrations.RemoveField(
            model_name='conditionrecord',
            name='snack_category',
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='snack_amount_1',
            field=models.IntegerField(null=True, verbose_name='おやつ1の量'),
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='snack_amount_2',
            field=models.IntegerField(null=True, verbose_name='おやつ2の量'),
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='snack_amount_3',
            field=models.IntegerField(null=True, verbose_name='おやつ3の量'),
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='snack_category_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snack_category_1', to='record.snackcategory', verbose_name='おやつ1の種類'),
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='snack_category_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snack_category_2', to='record.snackcategory', verbose_name='おやつ2の種類'),
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='snack_category_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snack_category_3', to='record.snackcategory', verbose_name='おやつ3の種類'),
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='snack_unit_1',
            field=models.CharField(blank=True, choices=[('gram', 'g'), ('pack', '袋'), ('stick', '本'), ('piece', '個')], max_length=50, null=True, verbose_name='おやつ1の量の単位'),
        ),
        migrations.AddField(
            model_name='conditionrecord',
            name='snack_unit_2',
            field=models.CharField(blank=True, choices=[('gram', 'g'), ('pack', '袋'), ('stick', '本'), ('piece', '個')], max_length=50, null=True, verbose_name='おやつ2の量の単位'),
        ),
    ]
