# Generated by Django 4.2.4 on 2023-11-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_rename_snack_unit_conditionrecord_snack_unit_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionrecord',
            name='food_amount_bf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='朝ごはんの量'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='food_amount_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='夕ごはんの量'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='food_amount_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='昼ごはんの量'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='snack_amount_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='おやつ1の量'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='snack_amount_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='おやつ2の量'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='snack_amount_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='おやつ3の量'),
        ),
    ]
