# Generated by Django 4.2.4 on 2023-11-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_alter_conditionrecord_food_amount_bf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionrecord',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='体重'),
        ),
    ]
