# Generated by Django 4.2.4 on 2023-11-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_alter_conditionrecord_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionrecord',
            name='food_unit_bf',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('袋', '袋'), ('本', '本'), ('個', '個')], max_length=50, null=True, verbose_name='朝ごはんの量の単位'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='food_unit_d',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('袋', '袋'), ('本', '本'), ('個', '個')], max_length=50, null=True, verbose_name='夕ごはんの量の単位'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='food_unit_l',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('袋', '袋'), ('本', '本'), ('個', '個')], max_length=50, null=True, verbose_name='昼ごはんの量の単位'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='snack_unit_1',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('袋', '袋'), ('本', '本'), ('個', '個')], max_length=50, null=True, verbose_name='おやつ1の量の単位'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='snack_unit_2',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('袋', '袋'), ('本', '本'), ('個', '個')], max_length=50, null=True, verbose_name='おやつ2の量の単位'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='snack_unit_3',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('袋', '袋'), ('本', '本'), ('個', '個')], max_length=50, null=True, verbose_name='おやつ3の量の単位'),
        ),
    ]
