# Generated by Django 4.2.4 on 2023-11-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_alter_conditionrecord_food_unit_bf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionrecord',
            name='stool_amount',
            field=models.CharField(choices=[('すごく多い', 'すごく多い'), ('多い', '多い'), ('いつも通り', 'いつも通り'), ('少ない', '少ない'), ('すごく少ない', 'すごく少ない')], max_length=50, verbose_name='便の量'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='urine_amount',
            field=models.CharField(choices=[('すごく多い', 'すごく多い'), ('多い', '多い'), ('いつも通り', 'いつも通り'), ('少ない', '少ない'), ('すごく少ない', 'すごく少ない')], max_length=50, verbose_name='尿の量'),
        ),
    ]
