# Generated by Django 4.2.4 on 2023-11-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_alter_conditionrecord_stool_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionrecord',
            name='clinic',
            field=models.CharField(choices=[('通院日', '通院日'), ('通院なし', '通院なし')], max_length=50, verbose_name='通院日'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='cut_nail',
            field=models.CharField(choices=[('爪を切った', '爪を切った'), ('爪切ってない', '爪切ってない')], max_length=50, verbose_name='爪切り'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='damage',
            field=models.CharField(choices=[('すごく良い', 'すごく良い'), ('良い', '良い'), ('変わらず', '変わらず'), ('悪い', '悪い'), ('すごく悪い', 'すごく悪い')], max_length=50, verbose_name='傷の状態'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='physical_condition',
            field=models.CharField(choices=[('すごく良い', 'すごく良い'), ('良い', '良い'), ('変わらず', '変わらず'), ('悪い', '悪い'), ('すごく悪い', 'すごく悪い')], max_length=50, verbose_name='元気度数'),
        ),
        migrations.AlterField(
            model_name='conditionrecord',
            name='stool_condition',
            field=models.CharField(choices=[('カチコチ', 'カチコチ'), ('カタ', 'カタ'), ('いつも通り', 'いつも通り'), ('ヤワ', 'ヤワ'), ('シャバシャバ', 'シャバシャバ')], max_length=50, verbose_name='便の状態'),
        ),
    ]
